"""Check screenshot pairs generated by rounded-taskbar-shell.js."""
import json
import math
from pathlib import Path
import sys
from PIL import Image

root = Path(sys.argv[1])
for bounds in json.loads((root / 'rounded-bounds.json').read_text()):
    edge = bounds['edge']
    before = Image.open(root / f'rounded-{edge}-before.png').convert('RGB')
    after = Image.open(root / f'rounded-{edge}-after.png').convert('RGB')
    x, y, w, h, radius = (round(bounds[k]) for k in ('x', 'y', 'width', 'height', 'radius'))
    checked = 0
    for dx in range(radius):
        for dy in range(radius):
            if math.hypot(radius - dx - .5, radius - dy - .5) < radius + 2:
                continue
            for px, py in ((x + dx, y + dy), (x + w - 1 - dx, y + dy),
                           (x + dx, y + h - 1 - dy), (x + w - 1 - dx, y + h - 1 - dy)):
                a, b = before.getpixel((px, py)), after.getpixel((px, py))
                assert max(abs(a[i] - b[i]) for i in range(3)) <= 3, (edge, px, py, a, b)
                checked += 1
    # Ensure content was actually painted rather than hidden by the test.
    assert any(max(abs(before.getpixel((px, py))[i] - after.getpixel((px, py))[i]) for i in range(3)) > 50
               for px in range(x + w // 3, x + 2 * w // 3)
               for py in range(y + h // 3, y + 2 * h // 3)), edge
    print(f'{edge}: {checked} outside-corner pixels unchanged')

bounds = json.loads((root / 'rounded-bounds.json').read_text())[0]
point = (round(bounds['x'] + bounds['width'] / 2), round(bounds['y'] + bounds['height'] / 2))
reference = Image.open(root / 'rounded-bottom-after.png').convert('RGB').getpixel(point)
for radius in (1, 0.49, 0.25, 0.01, 0):
    pixel = Image.open(root / f'rounded-radius-{radius}.png').convert('RGB').getpixel(point)
    assert max(abs(a - b) for a, b in zip(reference, pixel)) <= 3, (radius, reference, pixel)
print('Subpixel corner radii preserve full interior opacity')
