#!/usr/bin/env python3
"""Extract gettext catalogs or compile contributed translations (build tooling only)."""
import argparse
import json
from pathlib import Path
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parent.parent
DOMAIN = json.loads((ROOT / 'metadata.json').read_text())['gettext-domain']
PO = ROOT / 'po'

def run(*args):
    subprocess.run(args, cwd=ROOT, check=True)

def update():
    PO.mkdir(exist_ok=True)
    files = sorted(str(p.relative_to(ROOT)) for p in (ROOT / 'src').rglob('*') if p.suffix in ('.js', '.ts'))
    # Built-in widget manifests are data; their display fields share our domain.
    markers = ['// Generated by translations:update; edit the widget manifests instead.']
    def fields(value):
        if isinstance(value, dict):
            for key, item in value.items():
                if key in ('name', 'label', 'description') and isinstance(item, str):
                    markers.append('N_(' + json.dumps(item, ensure_ascii=False) + ');')
                else:
                    fields(item)
        elif isinstance(value, list):
            for item in value:
                fields(item)
    for manifest in sorted((ROOT / 'src/desktop/widgets').glob('*/widget.json')):
        markers.append('// ' + str(manifest.relative_to(ROOT)))
        fields(json.loads(manifest.read_text()))
    if len(markers) > 1:
        (PO / 'widget-strings.js').write_text('\n'.join(markers) + '\n')
        files.append('po/widget-strings.js')
    run('xgettext', '--language=JavaScript', '--from-code=UTF-8', '--sort-by-file',
        '--keyword=_', '--keyword=N_', '--keyword=ngettext:1,2', '--keyword=pgettext:1c,2',
        '--flag=_:1:pass-javascript-format', '--flag=ngettext:1:pass-javascript-format',
        '--flag=ngettext:2:pass-javascript-format', '--flag=formatText:1:javascript-format',
        '--add-comments=Translators:', '--package-name=' + DOMAIN,
        '--copyright-holder=Wuild', '--msgid-bugs-address=https://github.com/wuild',
        '--output=po/' + DOMAIN + '.pot', *files)
    for catalog in sorted(PO.glob('*.po')):
        run('msgmerge', '--update', '--backup=none', str(catalog), str(PO / (DOMAIN + '.pot')))

def compile_catalogs(destination):
    for catalog in sorted(PO.glob('*.po')):
        language = catalog.stem
        if not language or not language[0].isalpha() or not all(c.isalnum() or c in '_@.-' for c in language):
            raise ValueError('Invalid locale name: ' + language)
        target = destination / language / 'LC_MESSAGES' / (DOMAIN + '.mo')
        target.parent.mkdir(parents=True, exist_ok=True)
        run('msgfmt', '--check', '--check-format', '-o', str(target), str(catalog))

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('action', choices=['update', 'compile', 'check'])
parser.add_argument('--output', type=Path, default=ROOT / 'dist/locale')
args = parser.parse_args()
if args.action == 'update':
    update()
elif args.action == 'compile':
    compile_catalogs(args.output)
else:
    with tempfile.TemporaryDirectory() as temporary:
        compile_catalogs(Path(temporary))
