// Generated by scripts/generate-settings.py. Edit the XML schema instead.
export interface SettingsValues {
    "taskbar-position": "bottom" | "top" | "left" | "right";
    "taskbar-border-enabled": boolean;
    "taskbar-border-width": number;
    "taskbar-border-opacity": number;
    "taskbar-border-color": string;
    "taskbar-floating": boolean;
    "window-appearance-layout": "inherit" | "attached" | "floating";
    "taskbar-edge-gap": number;
    "taskbar-start-padding": number;
    "taskbar-end-padding": number;
    "taskbar-end-gap": number;
    "taskbar-corner-radius": number;
    "window-appearance-edge-gap": number;
    "window-appearance-end-gap": number;
    "window-appearance-corner-radius": number;
    "tray-always-visible": string[];
    "tray-icon-order": string[];
    "tray-known-items": string;
    "taskbar-color-override": boolean;
    "panel-color-override": boolean;
    "window-appearance-color-override": boolean;
    "app-button-width": number;
    "launcher-padding": number;
    "launcher-margin": number;
    "tray-icon-size": number;
    "tray-text-size": number;
    "window-appearance-mode": "disabled" | "near" | "maximized" | "either";
    "window-appearance-distance": number;
    "window-appearance-color": string;
    "window-appearance-opacity": number;
    "window-appearance-blur": boolean;
    "window-appearance-blur-radius": number;
    "taskbar-color": string;
    "panel-color": string;
    "indicator-color-mode": "default" | "custom" | "app";
    "indicator-color": string;
    "visibility-mode": "always" | "auto-hide" | "maximized" | "overlap";
    "hide-delay": number;
    "monitor-mode": "primary" | "all" | "specific";
    "monitor-connector": string;
    "monitor-index": number;
    "monitor-local-windows": boolean;
    "show-desktop-margin": number;
    "overview-panel-opacity": number;
    "overview-tint-opacity": number;
    "overview-taskbar-gap": number;
    "taskbar-height": number;
    "app-spacing": number;
    "tray-show-passive": boolean;
    "tray-collapse-enabled": boolean;
    "tray-visible-limit": number;
    "tray-spacing": number;
    "applet-spacing": number;
    "show-desktop-width": number;
    "panel-edge-gap": number;
    "panel-taskbar-gap": number;
    "panel-corner-radius": number;
    "preview-show-delay": number;
    "preview-hide-delay": number;
    "preview-padding": number;
    "preview-card-spacing": number;
    "show-desktop-button": boolean;
    "running-indicators": boolean;
    "menu-show-applications": boolean;
    "menu-show-desktop": boolean;
    "menu-show-shortcut": boolean;
    "menu-shortcut-app": string;
    "calendar-week-numbers": boolean;
    "calendar-collapsed": boolean;
    "calendar-week-start": "system" | "monday" | "sunday";
    "tray-popup-icon-size": number;
    "clock-layout": "two-line" | "single-line";
    "system-hidden-icons": string[];
    "separate-applet-panels": boolean;
    "unified-system-panel": boolean;
    "applet-padding": number;
    "applet-order": string[];
    "show-previews": boolean;
    "enable-blur": boolean;
    "show-overview-button": boolean;
    "overview-button-icon": string;
    "launcher-menu": "overview" | "arcmenu";
    "launcher-icon": "grid" | "distro" | "custom";
    "custom-launcher-icon": string;
    "launcher-size": number;
    "overview-blur": boolean;
    "app-margin": number;
    "app-padding": number;
    "app-icon-size": number;
    "preview-width": number;
    "preview-aspect-ratio": "16:10" | "16:9" | "4:3" | "window";
    "panel-transparency": boolean;
    "taskbar-blur-radius": number;
    "taskbar-opacity": number;
    "panel-blur-radius": number;
    "panel-opacity": number;
    "overview-blur-radius": number;
    "notification-badges": boolean;
    "search-button-width": number;
    "search-button-padding": number;
    "search-button-margin": number;
    "search-icon-size": number;
    "search-shortcut": string[];
    "show-search-button": boolean;
    "app-hover-animation": "none" | "lift" | "zoom";
    "app-animation-duration": number;
    "app-appear-animation": boolean;
    "app-launch-animation": boolean;
    "app-close-animation": boolean;
    "search-panel-enabled": boolean;
    "taskbar-scroll-workspaces": boolean;
    "show-workspace-switcher": boolean;
    "app-click-action": "default" | "cycle" | "activate" | "toggle-group" | "minimize" | "new-window" | "previews" | "menu" | "none";
    "app-middle-click-action": "default" | "cycle" | "activate" | "toggle-group" | "minimize" | "new-window" | "previews" | "menu" | "none";
    "app-right-click-action": "default" | "cycle" | "activate" | "toggle-group" | "minimize" | "new-window" | "previews" | "menu" | "none";
    "app-shift-click-action": "default" | "cycle" | "activate" | "toggle-group" | "minimize" | "new-window" | "previews" | "menu" | "none";
    "app-scroll-action": "strip" | "cycle" | "workspaces" | "none";
    "show-weather": boolean;
    "weather-separate-button": boolean;
    "weather-slim": boolean;
    "weather-city": string;
    "weather-country": string;
    "weather-units": "celsius" | "fahrenheit";
}

export const settingDefinitions = {
    "taskbar-position": {
        "type": "s",
        "choices": [
            "bottom",
            "top",
            "left",
            "right"
        ]
    },
    "taskbar-border-enabled": {
        "type": "b"
    },
    "taskbar-border-width": {
        "type": "i",
        "range": [
            1,
            8
        ]
    },
    "taskbar-border-opacity": {
        "type": "i",
        "range": [
            0,
            100
        ]
    },
    "taskbar-border-color": {
        "type": "s"
    },
    "taskbar-floating": {
        "type": "b"
    },
    "window-appearance-layout": {
        "type": "s",
        "choices": [
            "inherit",
            "attached",
            "floating"
        ]
    },
    "taskbar-edge-gap": {
        "type": "i",
        "range": [
            0,
            200
        ]
    },
    "taskbar-start-padding": {
        "type": "i",
        "range": [
            0,
            200
        ]
    },
    "taskbar-end-padding": {
        "type": "i",
        "range": [
            0,
            200
        ]
    },
    "taskbar-end-gap": {
        "type": "i",
        "range": [
            0,
            400
        ]
    },
    "taskbar-corner-radius": {
        "type": "i",
        "range": [
            0,
            100
        ]
    },
    "window-appearance-edge-gap": {
        "type": "i",
        "range": [
            0,
            200
        ]
    },
    "window-appearance-end-gap": {
        "type": "i",
        "range": [
            0,
            400
        ]
    },
    "window-appearance-corner-radius": {
        "type": "i",
        "range": [
            0,
            100
        ]
    },
    "tray-always-visible": {
        "type": "as"
    },
    "tray-icon-order": {
        "type": "as"
    },
    "tray-known-items": {
        "type": "s"
    },
    "taskbar-color-override": {
        "type": "b"
    },
    "panel-color-override": {
        "type": "b"
    },
    "window-appearance-color-override": {
        "type": "b"
    },
    "app-button-width": {
        "type": "i",
        "range": [
            16,
            120
        ]
    },
    "launcher-padding": {
        "type": "i",
        "range": [
            0,
            24
        ]
    },
    "launcher-margin": {
        "type": "i",
        "range": [
            0,
            24
        ]
    },
    "tray-icon-size": {
        "type": "i",
        "range": [
            12,
            48
        ]
    },
    "tray-text-size": {
        "type": "i",
        "range": [
            8,
            24
        ]
    },
    "window-appearance-mode": {
        "type": "s",
        "choices": [
            "disabled",
            "near",
            "maximized",
            "either"
        ]
    },
    "window-appearance-distance": {
        "type": "i",
        "range": [
            0,
            200
        ]
    },
    "window-appearance-color": {
        "type": "s"
    },
    "window-appearance-opacity": {
        "type": "i",
        "range": [
            0,
            100
        ]
    },
    "window-appearance-blur": {
        "type": "b"
    },
    "window-appearance-blur-radius": {
        "type": "i",
        "range": [
            0,
            100
        ]
    },
    "taskbar-color": {
        "type": "s"
    },
    "panel-color": {
        "type": "s"
    },
    "indicator-color-mode": {
        "type": "s",
        "choices": [
            "default",
            "custom",
            "app"
        ]
    },
    "indicator-color": {
        "type": "s"
    },
    "visibility-mode": {
        "type": "s",
        "choices": [
            "always",
            "auto-hide",
            "maximized",
            "overlap"
        ]
    },
    "hide-delay": {
        "type": "i",
        "range": [
            0,
            2000
        ]
    },
    "monitor-mode": {
        "type": "s",
        "choices": [
            "primary",
            "all",
            "specific"
        ]
    },
    "monitor-connector": {
        "type": "s"
    },
    "monitor-index": {
        "type": "i",
        "range": [
            0,
            15
        ]
    },
    "monitor-local-windows": {
        "type": "b"
    },
    "show-desktop-margin": {
        "type": "i",
        "range": [
            0,
            24
        ]
    },
    "overview-panel-opacity": {
        "type": "i",
        "range": [
            0,
            100
        ]
    },
    "overview-tint-opacity": {
        "type": "i",
        "range": [
            0,
            80
        ]
    },
    "overview-taskbar-gap": {
        "type": "i",
        "range": [
            0,
            48
        ]
    },
    "taskbar-height": {
        "type": "i",
        "range": [
            32,
            100
        ]
    },
    "app-spacing": {
        "type": "i",
        "range": [
            0,
            24
        ]
    },
    "tray-show-passive": {
        "type": "b"
    },
    "tray-collapse-enabled": {
        "type": "b"
    },
    "tray-visible-limit": {
        "type": "i",
        "range": [
            1,
            20
        ]
    },
    "tray-spacing": {
        "type": "i",
        "range": [
            0,
            24
        ]
    },
    "applet-spacing": {
        "type": "i",
        "range": [
            0,
            24
        ]
    },
    "show-desktop-width": {
        "type": "i",
        "range": [
            4,
            32
        ]
    },
    "panel-edge-gap": {
        "type": "i",
        "range": [
            0,
            48
        ]
    },
    "panel-taskbar-gap": {
        "type": "i",
        "range": [
            0,
            32
        ]
    },
    "panel-corner-radius": {
        "type": "i",
        "range": [
            0,
            32
        ]
    },
    "preview-show-delay": {
        "type": "i",
        "range": [
            0,
            1500
        ]
    },
    "preview-hide-delay": {
        "type": "i",
        "range": [
            0,
            1000
        ]
    },
    "preview-padding": {
        "type": "i",
        "range": [
            0,
            24
        ]
    },
    "preview-card-spacing": {
        "type": "i",
        "range": [
            0,
            24
        ]
    },
    "show-desktop-button": {
        "type": "b"
    },
    "running-indicators": {
        "type": "b"
    },
    "menu-show-applications": {
        "type": "b"
    },
    "menu-show-desktop": {
        "type": "b"
    },
    "menu-show-shortcut": {
        "type": "b"
    },
    "menu-shortcut-app": {
        "type": "s"
    },
    "calendar-week-numbers": {
        "type": "b"
    },
    "calendar-collapsed": {
        "type": "b"
    },
    "calendar-week-start": {
        "type": "s",
        "choices": [
            "system",
            "monday",
            "sunday"
        ]
    },
    "tray-popup-icon-size": {
        "type": "i",
        "range": [
            12,
            48
        ]
    },
    "clock-layout": {
        "type": "s",
        "choices": [
            "two-line",
            "single-line"
        ]
    },
    "system-hidden-icons": {
        "type": "as"
    },
    "separate-applet-panels": {
        "type": "b"
    },
    "unified-system-panel": {
        "type": "b"
    },
    "applet-padding": {
        "type": "i",
        "range": [
            0,
            24
        ]
    },
    "applet-order": {
        "type": "as"
    },
    "show-previews": {
        "type": "b"
    },
    "enable-blur": {
        "type": "b"
    },
    "show-overview-button": {
        "type": "b"
    },
    "overview-button-icon": {
        "type": "s"
    },
    "launcher-menu": {
        "type": "s",
        "choices": [
            "overview",
            "arcmenu"
        ]
    },
    "launcher-icon": {
        "type": "s",
        "choices": [
            "grid",
            "distro",
            "custom"
        ]
    },
    "custom-launcher-icon": {
        "type": "s"
    },
    "launcher-size": {
        "type": "i",
        "range": [
            20,
            36
        ]
    },
    "overview-blur": {
        "type": "b"
    },
    "app-margin": {
        "type": "i",
        "range": [
            0,
            16
        ]
    },
    "app-padding": {
        "type": "i",
        "range": [
            0,
            16
        ]
    },
    "app-icon-size": {
        "type": "i",
        "range": [
            16,
            64
        ]
    },
    "preview-width": {
        "type": "i",
        "range": [
            160,
            480
        ]
    },
    "preview-aspect-ratio": {
        "type": "s",
        "choices": [
            "16:10",
            "16:9",
            "4:3",
            "window"
        ]
    },
    "panel-transparency": {
        "type": "b"
    },
    "taskbar-blur-radius": {
        "type": "i",
        "range": [
            0,
            100
        ]
    },
    "taskbar-opacity": {
        "type": "i",
        "range": [
            0,
            100
        ]
    },
    "panel-blur-radius": {
        "type": "i",
        "range": [
            0,
            100
        ]
    },
    "panel-opacity": {
        "type": "i",
        "range": [
            0,
            100
        ]
    },
    "overview-blur-radius": {
        "type": "i",
        "range": [
            0,
            100
        ]
    },
    "notification-badges": {
        "type": "b"
    },
    "search-button-width": {
        "type": "i",
        "range": [
            16,
            120
        ]
    },
    "search-button-padding": {
        "type": "i",
        "range": [
            0,
            16
        ]
    },
    "search-button-margin": {
        "type": "i",
        "range": [
            0,
            16
        ]
    },
    "search-icon-size": {
        "type": "i",
        "range": [
            12,
            64
        ]
    },
    "search-shortcut": {
        "type": "as"
    },
    "show-search-button": {
        "type": "b"
    },
    "app-hover-animation": {
        "type": "s",
        "choices": [
            "none",
            "lift",
            "zoom"
        ]
    },
    "app-animation-duration": {
        "type": "i",
        "range": [
            0,
            500
        ]
    },
    "app-appear-animation": {
        "type": "b"
    },
    "app-launch-animation": {
        "type": "b"
    },
    "app-close-animation": {
        "type": "b"
    },
    "search-panel-enabled": {
        "type": "b"
    },
    "taskbar-scroll-workspaces": {
        "type": "b"
    },
    "show-workspace-switcher": {
        "type": "b"
    },
    "app-click-action": {
        "type": "s",
        "choices": [
            "default",
            "cycle",
            "activate",
            "toggle-group",
            "minimize",
            "new-window",
            "previews",
            "menu",
            "none"
        ]
    },
    "app-middle-click-action": {
        "type": "s",
        "choices": [
            "default",
            "cycle",
            "activate",
            "toggle-group",
            "minimize",
            "new-window",
            "previews",
            "menu",
            "none"
        ]
    },
    "app-right-click-action": {
        "type": "s",
        "choices": [
            "default",
            "cycle",
            "activate",
            "toggle-group",
            "minimize",
            "new-window",
            "previews",
            "menu",
            "none"
        ]
    },
    "app-shift-click-action": {
        "type": "s",
        "choices": [
            "default",
            "cycle",
            "activate",
            "toggle-group",
            "minimize",
            "new-window",
            "previews",
            "menu",
            "none"
        ]
    },
    "app-scroll-action": {
        "type": "s",
        "choices": [
            "strip",
            "cycle",
            "workspaces",
            "none"
        ]
    },
    "show-weather": {
        "type": "b"
    },
    "weather-separate-button": {
        "type": "b"
    },
    "weather-slim": {
        "type": "b"
    },
    "weather-city": {
        "type": "s"
    },
    "weather-country": {
        "type": "s"
    },
    "weather-units": {
        "type": "s",
        "choices": [
            "celsius",
            "fahrenheit"
        ]
    }
} as const;
export type SettingKey = keyof SettingsValues;
export type KeysOfType<T> = {[K in SettingKey]: SettingsValues[K] extends T ? K : never}[SettingKey];
export const taskbarKeys = Object.keys(settingDefinitions) as SettingKey[];
